site_name: Backend Engineering Notes

theme:
  name: material
  logo: false
  favicon: false
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    scheme: slate

plugins:
  - search

extra_css:
  - assets/stylesheets/custom.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Java:
      - Collections: java/collection.md
      - Java Core: java/java-core.md
      - JVM Internals: java/jvm.md
      - Concurrency: java/concurrency.md
  - Spring:
      - Overview: spring/spring.md
  - Persistence:
      - Hibernate: persistence/hibernate.md
  - Databases:
      - ACID: databases/acid.md
      - Isolation Levels: databases/isolation-levels.md
      - Indexing: databases/indexing.md
      - Query Optimization: databases/query-optimization.md
      - Transactions: databases/transactions.md
  - Messaging:
      - Kafka: messaging/kafka.md
  - Kubernetes:
      - Kubernetes: kubernetes/kubernetes.md
  - System Design:
      - System Design: system-design/system-design.md
